// <auto-generated />
using System;
using BudgetPlannerWPF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlannerWPF.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20251207191039_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlannerWPF.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int?>("YearlyMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasDiscriminator().HasValue("Expense");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Amount = 650m,
                            Category = 0,
                            Date = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Matinköp Coop",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 8200m,
                            Category = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hyra",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 940m,
                            Category = 2,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Busskort",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 540m,
                            Category = 4,
                            Date = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vaccination hund",
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("BudgetPlannerWPF.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsYearlyIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int?>("YearlyMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Incomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 32000m,
                            Category = 0,
                            Date = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsYearlyIncome = false,
                            Title = "Månadslön",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1200m,
                            Category = 2,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsYearlyIncome = false,
                            Title = "Hobbyförsäljning",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 6000m,
                            Category = 1,
                            Date = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsYearlyIncome = true,
                            Title = "Julbonus",
                            TransactionType = 2,
                            YearlyMonth = 12
                        },
                        new
                        {
                            Id = 4,
                            Amount = 800m,
                            Category = 3,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsYearlyIncome = false,
                            Title = "Födelsedagspresent",
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("BudgetPlannerWPF.Models.RecurringExpense", b =>
                {
                    b.HasBaseType("BudgetPlannerWPF.Models.Expense");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RecurringExpense");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Amount = 129m,
                            Category = 6,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Netflix",
                            TransactionType = 1,
                            Interval = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 4200m,
                            Category = 2,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bilförsäkring",
                            TransactionType = 2,
                            YearlyMonth = 1,
                            Interval = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 299m,
                            Category = 5,
                            Date = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gymkort",
                            TransactionType = 1,
                            Interval = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 189m,
                            Category = 3,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barnförsäkring",
                            TransactionType = 1,
                            Interval = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
